### ISSUE TITLE
Future of this split

### ISSUE THREAD

**Issue by dpfaffenbauer** [okvpn/migration-bundle#3]
Hi guys,

I really like the idea of subtree splitting ORO Migrations and remove dependencies. It is a great Bundle. But, what I am concerned about is: What is the future of this fork? Are you going to pull from ORO? Make changes yourself? Or leave it, as it is?

Regards
Dominik

**Comment by vtsykun** [comment]
Hi, @dpfaffenbauer 
Yes, we will maintained this fork.

Thanks,
Vladimir
